services:
  - type: web
    name: message-app
    env: static
    buildCommand: "chmod +x build.sh && ./build.sh"
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 