services:
  - type: web
    name: message-app
    env: static
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 